### ISSUE TITLE
扩展程序无法启动，提示扩展程序启动失败，请稍后再试

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#1042]
**公司名称**
德施曼

**是否为新产品**
是

**产品名称/Model**
德施曼Q3智能锁/dsm.lock.r5

**环境**
- 电脑操作系统:  mac
- 手机系统:  google Pixel
- SDK分支:   10010
- 相关模块:  米家App 5.5.16.2测试版

**现象**
设备注册成功后，首页卡片点击后报错，提示“提示扩展程序启动失败，请稍后再试”

**期望**
能正常进入插件

**相关日志**
对应的logcag控制台日志如下：
2019-06-23 10:23:19.802 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=zwuBIvX9Q2aZlhKyv59eiA
2019-06-23 10:23:19.803 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: {"88382919":["prop.power","event.dev_online","event.dev_offline"]}
2019-06-23 10:23:19.903 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=le5nYpVLQzKgCEbqxtw_1Q
2019-06-23 10:23:19.903 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: {"88382919":["prop.2.1","event.dev_online","event.dev_offline"]}
2019-06-23 10:23:19.930 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: onStartNestedScroll
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err: java.lang.NoSuchFieldException: No field mLastNestedScrollingChildRef in class Landroid/support/design/widget/AppBarLayout$Behavior; (declaration of 'android.support.design.widget.AppBarLayout$Behavior' appears in base.apk!classes2.dex)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.design.widget.AppBarLayoutSpringBehavior.setLastNestedScrollingChildRef(SourceFile:114)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.design.widget.AppBarLayoutSpringBehavior.onStartNestedScroll(SourceFile:107)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.design.widget.AppBarLayoutSpringBehavior.onStartNestedScroll(SourceFile:32)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.design.widget.CoordinatorLayout.onStartNestedScroll(SourceFile:1746)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.v4.view.ViewParentCompat.onStartNestedScroll(SourceFile:178)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.v4.view.NestedScrollingChildHelper.startNestedScroll(SourceFile:153)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.v7.widget.RecyclerView.startNestedScroll(SourceFile:11281)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(SourceFile:3022)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
2019-06-23 10:23:19.931 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at com.xiaomi.smarthome.newui.widget.MainCoordinatorLayout.dispatchTouchEvent(SourceFile:28)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.View.dispatchPointerEvent(View.java:12752)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5107)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4910)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4586)
2019-06-23 10:23:19.932 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4643)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7093)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7062)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7023)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7196)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:326)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.os.Looper.loop(Looper.java:160)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: onStartNestedScroll started=true
2019-06-23 10:23:19.933 25686-25686/com.xiaomi.smarthome D/MyFabBehavior: onStartNestedScroll   viewY true   coordinatorLayout.getHeight()  1650   child.getY()  1350.0
2019-06-23 10:23:19.934 25686-25686/com.xiaomi.smarthome V/unknown:AbstractDraweeController: controller 91b7645 20: onTouchEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=140.0, y[0]=32.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=99095830, downTime=99095830, deviceId=8, source=0x1002 }
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: onStopNestedScroll mIsFling=0.0,mOffsetSpring=0.0,mOffset=0,abl.getHeight=302,mContentHeight=302
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: checkShouldSpringRecover
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: animation start 260
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.005 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.006 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.015 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.015 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.015 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.015 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.016 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.017 25686-25686/com.xiaomi.smarthome I/PluginStartTime: onClickHomeDevice  1561256600017
2019-06-23 10:23:20.022 25686-25686/com.xiaomi.smarthome I/RN_TIMESTAMP: device item clicked : 1561256600022
2019-06-23 10:23:20.023 25686-25686/com.xiaomi.smarthome I/stopScan: render stop
2019-06-23 10:23:20.032 25686-25686/com.xiaomi.smarthome I/Device_Renderer: 1 - 1561256600032
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome E/Device_Renderer: dsm.lock.r5, 0 - 1561256600041
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.041 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.049 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.049 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.049 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.049 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.049 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.095 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.095 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.095 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.095 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.096 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.114 25686-25686/com.xiaomi.smarthome V/miio-bluetooth: BLEDeviceManager onSearchCanceled
2019-06-23 10:23:20.118 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.118 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.118 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.118 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.119 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.133 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.133 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.133 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.133 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.133 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.150 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.150 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.150 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.150 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.150 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.166 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.166 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.166 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.166 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.167 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.183 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.183 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.183 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.183 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.183 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.200 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.200 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.200 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.200 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.200 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
2019-06-23 10:23:20.229 25686-25686/com.xiaomi.smarthome E/DeviceRenderer: Error{mCode=-1, mDetail=''}
2019-06-23 10:23:20.249 25686-25686/com.xiaomi.smarthome E/click_device_list: sendMessage-downloadPlugin-onFailure
2019-06-23 10:23:20.251 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset mOffset=0
2019-06-23 10:23:20.251 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: setHeaderTopBottomOffset3 mOffsetSpring=0.0,originNew=0
2019-06-23 10:23:20.251 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringOffsetByscroll
2019-06-23 10:23:20.251 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight 0.0,mOffset=0
2019-06-23 10:23:20.251 25686-25686/com.xiaomi.smarthome D/AppBarLayoutSpringBehavior: updateSpringHeaderHeight mPreHeadHeight=302,appBarLayout.getHeight()=302
    
    --------- beginning of system
2019-06-23 10:23:20.727 25686-25686/com.xiaomi.smarthome E/SmartHomeDeviceManager: startNotifySuccess: outer want to startNotifyRefresh, mIsRefreshing = false
2019-06-23 10:23:20.727 25686-25686/com.xiaomi.smarthome E/SmartHomeDeviceManager: updateInnerDevice, isDeviceReady = false
2019-06-23 10:23:20.727 25686-25686/com.xiaomi.smarthome D/SmartHomeDeviceManager: updateInnerDevice, isDeviceReady = false
2019-06-23 10:23:20.755 25686-25686/com.xiaomi.smarthome W/miio-bluetooth: getSmartHomeDevices ...
2019-06-23 10:23:20.759 25686-25686/com.xiaomi.smarthome W/miio-bluetooth: >>> name = R5, did = 1010966971, mac = E6:3A:06:E9:4F:ED, model = dsm.lock.r5, permit = 16, rssi = 0
2019-06-23 10:23:20.767 25686-25686/com.xiaomi.smarthome W/miio-bluetooth: >>> name = 创米小白智能门锁C1, did = 1010008840, mac = D1:66:D3:85:3A:28, model = chuangmi.lock.hmi501, permit = 16, rssi = 0
2019-06-23 10:23:20.770 25686-25926/com.xiaomi.smarthome D/SmartHomeDeviceManager: updateInnerDevice doInBackground
2019-06-23 10:23:20.771 25686-25926/com.xiaomi.smarthome D/SmartHomeDeviceManager: updateInnerDevice doInBackground 556
2019-06-23 10:23:20.773 25686-25926/com.xiaomi.smarthome D/SmartHomeDeviceManager: updateInnerDevice doInBackground 561
2019-06-23 10:23:20.776 25686-25926/com.xiaomi.smarthome D/SmartHomeDeviceManager: updateInnerDevice doInBackground 586
2019-06-23 10:23:20.778 25686-25686/com.xiaomi.smarthome E/SmartHomeDeviceManager: final devices to be notified size = 3, isDeviceReady = false
2019-06-23 10:23:20.778 25686-25686/com.xiaomi.smarthome D/SmartHomeDeviceManager: final devices to be notified size = 3, isDeviceReady = false
2019-06-23 10:23:20.780 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: UPDATE_DEVICE_DATA_READY getCurrentState 4,device size=3
2019-06-23 10:23:20.781 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: Device Data Is Ready,But View Not!
2019-06-23 10:23:20.782 25686-25686/com.xiaomi.smarthome E/AllCameraGroup: 0, 0
2019-06-23 10:23:20.782 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: adjustAppBarLayoutHeightIfNeed false
2019-06-23 10:23:20.783 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: UPDATE_DEVICE_DATA_READY mIsAdapterLoading=false,sHasBeenAdded=true
2019-06-23 10:23:20.784 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=null
2019-06-23 10:23:20.784 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=null
2019-06-23 10:23:20.785 25686-25918/com.xiaomi.smarthome E/device_rpc: Start Refresh PROP
2019-06-23 10:23:20.786 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=null
2019-06-23 10:23:20.787 25686-25686/com.xiaomi.smarthome D/DevicePropSubscriber: subscribe subid=null
2019-06-23 10:23:20.787 25686-25918/com.xiaomi.smarthome D/refresh: loadAllCameraCloudStorageInfoFromServer onFailure:-9005
2019-06-23 10:23:20.787 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: switch_refresh_success
2019-06-23 10:23:20.787 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: category_info_updated_action
2019-06-23 10:23:20.787 25686-25918/com.xiaomi.smarthome E/AllCamera: Empty
2019-06-23 10:23:20.788 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: adjustAppBarLayoutHeightIfNeed false
2019-06-23 10:23:20.789 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: notifyDataSetChanged
2019-06-23 10:23:20.791 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: showOffline true
2019-06-23 10:23:20.791 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: adjustAppBarLayoutHeightIfNeed false
2019-06-23 10:23:20.797 25686-25686/com.xiaomi.smarthome D/PageBean: wrapperCategory: is ready
2019-06-23 10:23:20.798 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: refreshPages rooms size=3
2019-06-23 10:23:20.799 25686-25686/com.xiaomi.smarthome D/RoomPagerAdapter: refresh: isDataReady: true
2019-06-23 10:23:20.799 25686-25686/com.xiaomi.smarthome E/RoomPagerAdapter: checkShowEmptyDeviceAd: 
2019-06-23 10:23:20.801 25686-25686/com.xiaomi.smarthome D/HomeManager: all size: 3
2019-06-23 10:23:20.802 25686-25686/com.xiaomi.smarthome D/HomeManager: all size: 3
2019-06-23 10:23:20.802 25686-25686/com.xiaomi.smarthome D/DeviceRecycler: changeToGridMode
2019-06-23 10:23:20.803 25686-25686/com.xiaomi.smarthome D/forceUpdateAllData: DeviceMainGridAdapter updateDataByDidList commonUseDids=3,alldevice=3
2019-06-23 10:23:20.804 25686-25686/com.xiaomi.smarthome D/DeviceRecycler: changeToGridMode
2019-06-23 10:23:20.805 25686-25686/com.xiaomi.smarthome D/forceUpdateAllData: DeviceMainGridAdapter updateDataByDidList commonUseDids=2,alldevice=2
2019-06-23 10:23:20.805 25686-25686/com.xiaomi.smarthome D/RoomPagerAdapter: refresh: refresh local: 7
2019-06-23 10:23:20.806 25686-25686/com.xiaomi.smarthome D/DeviceMainPage: adjustAppBarLayoutHeightIfNeed false
2019-06-23 10:23:21.293 25686-26399/com.xiaomi.smarthome E/WifiDeviceFinder: start process end time - 19
2019-06-23 10:23:21.301 25686-25975/com.xiaomi.smarthome E/WifiScanHomelog: start process end time - 24
2019-06-23 10:23:21.465 25686-25686/com.xiaomi.smarthome D/AppLifecycleManager: appQuit
2019-06-23 10:23:21.468 25686-25686/com.xiaomi.smarthome V/unknown:BitmapPool: release (free) (object, size) = (cc55793, 211600)
2019-06-23 10:23:21.472 25686-25686/com.xiaomi.smarthome V/unknown:BitmapPool: Used = (3, 338688); Free = (0, 0)
2019-06-23 10:23:21.474 25686-25686/com.xiaomi.smarthome V/unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (bc28b32, 4096)
2019-06-23 10:23:21.474 25686-25686/com.xiaomi.smarthome V/unknown:NativeMemoryChunkPool: Used = (0, 0); Free = (4, 32768)
2019-06-23 10:23:21.476 25686-25686/com.xiaomi.smarthome D/FrescoInitial: Fresco clearMemoryCaches

**Comment by dessmann** [comment]
问题找到了，R5未提交插件，也没有配置调试模式
