### ISSUE TITLE
iOS启动demo失败

### ISSUE THREAD

**Issue by bobby0224** [MiEcosystem/miot-plugin-sdk#1292]
**是否为新品（必填）**
新品

**关联的产品model**
zimi.clock.myk01

**项目ID（必填）**
无项目ID

**企业名称（必填）**
小米 电视部

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 11.0
- SDK分支: master
- 相关模块:demo

**现象（必填）**
无法启动demo。

**期望（必填）**
demo可以正常启动。

**其他的上下文/日志/截图**
error: bundling failed: Error: Unable to resolve module `react-native-root-toast` from `/Users/sysappsmac/work/test/miot-plugin-sdk/projects/com.xiaomi.demo/Main/UIComponent/ToastExample.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:1476)
    at ResolutionRequest.resolveDependency (/Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at /Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/sysappsmac/work/test/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] projects/com.xiaomi.demo/index.ios.js ░░░░░░░░░░░░░░░░ 2.9% (89/523), failed.

**尝试过的解决办法**
按照出错信息里的提示进行了操作， 没有效果

**Comment by bobby0224** [comment]
单独安装了下 react-native-root-toast之后好了。
npm install react-native-root-toast --save

npm install的时候报了不少错误， 提示进行fix， 但是fix了的话就npm start就会失败。
不知道是不是跟这个有关系

**Comment by zanetti4** [comment]
错误信息说的就是缺少 react-native-root-toast 模块。

**Comment by zanetti4** [comment]
@santcool package.json 里没有这个模块，开发者想要运行 demo 的话，都要自行安装 react-native-root-toast 吗？

**Comment by santcool** [comment]
已更新相关文档。
