### ISSUE TITLE
插件崩溃反馈

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#1302]
紧急优先级

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
是
- SDK 是否更新到最新？
是
- Check 文档了吗？
是
- 是否尝试搜索issue？
是
- 是否尝试搜索“常见问题”
是
---
**是否为新品（必填）**
填 新品 or 在售
在售

**项目ID（必填）**
米家新风机

**企业名称（必填）**
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 8.1
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。
米家测试在后台日志统计，反馈了一些崩溃日志，崩溃率超标。具体日志信息见后面。

**期望（必填）**
消除崩溃

**其他的上下文/日志/截图**
日志1
``````3 ===plugin crash===
pluginType=ReactNative
pluginId=1000316
pkgId=1027528
rnSdkApiLevel=10022
rnSdkBuildTime=1562065919000
rnSdkIsInner=true
userId=6191077976
com.facebook.react.common.JavascriptException: TypeError: TypeError: null is not an object (evaluating '_interpolate.first')

This error is located at:
    in StackViewLayout
    in withOrientation
    in RCTView
    in Transitioner
    in StackView
    in Navigator
    in KeyboardAwareNavigator
    in NavigationContainer
    in App
    in RCTView
    in PackageRoot
    in RCTView
    in RCTView
    in AppContainer

This error is located at:
    in NavigationContainer
    in App
    in RCTView
    in PackageRoot
    in RCTView
    in RCTView
    in AppContainer, stack:
_renderCard@-1:61
<unknown>@-1:40
map@-1
render@-1:23
finishClassComponent@-1:269
beginWork@-1:40
performUnitOfWork@-1:27
renderRoot@-1:47
performWorkOnRoot@-1:447
performWork@-1:26
requestWork@-1:193
scheduleWork@-1:58
enqueueSetState@-1:21
setState@-1:33
_onTransitionEnd@-1:22
cb@-1:35
<unknown>@-1:31
__debouncedOnEnd@-1:23
__debouncedOnEnd@-1
__invokeCallback@-1:23
<unknown>@-1:34
__guardSafe@-1:13
invokeCallbackAndReturnFlushedQueue@-1:21
invokeCallbackAndReturnFlushedQueue@-1

 at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(SourceFile:56)
 at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(SourceFile:40)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:374)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:162)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:794)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
 at android.os.Looper.loop(Looper.java:176)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
 at java.lang.Thread.run(Thread.java:764)
``````
日志2：
``````
137 ===plugin crash===
pluginType=ReactNative
pluginId=1000316
pkgId=1000529
rnSdkApiLevel=10022
rnSdkBuildTime=1562065919000
rnSdkIsInner=true
userId=829174557
java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.react.uimanager.ThemedReactContext com.facebook.react.uimanager.ReactShadowNode.getThemedContext()' on a null object reference
 at com.facebook.react.uimanager.UIImplementation.createView(SourceFile:282)
 at com.facebook.react.uimanager.UIManagerModule.createView(SourceFile:364)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:374)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:162)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:754)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
 at android.os.Looper.loop(Looper.java:163)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
 at java.lang.Thread.run(Thread.java:760)
``````

**尝试过的解决办法**
尝试过调试代码，未为找到异常的出现的原因，也没找到解决办法。

希望提供崩溃解决的办法。谢谢

**Comment by fishle** [comment]
iOS 试过吗

**Comment by lvjie0519** [comment]
@evansherry  线下也沟通过，看代码及如上错误日志，不太好排查问题，麻烦你那边沟通下请qa提供下测试场景，方便复现， 谢谢。

**Comment by evansherry** [comment]
@fishle 目前反馈都是android的崩溃日志

**Comment by evansherry** [comment]
@lvjie0519 这个不是测试测出来的，是后台日志记录，然后测试统计反馈给我这边

**Comment by lvjie0519** [comment]
@evansherry  请把你们的main.bundle 文件通过微信发给我，微信号(sky-boy-0519)。

**Comment by lvjie0519** [comment]
@evansherry    线下已沟通， 问题修复后，插件包上传到开发者平台，多测试测试吧，看是否还会出现其他崩溃日志，不方便查看崩溃日志，可以让我帮忙查看，谢谢。

**Comment by evansherry** [comment]
@lvjie0519 问题1应该修复了，我这边再观察一下，问题2怎么定位呀

**Comment by lvjie0519** [comment]
@evansherry  问题2， 看不出是否有js代码导致的，看时间上报上，两个问题时间差不多，不太确定是否为第一个问题导致了第二个问题，先修复了第一个问题，第二个问题测试待观察吧。

**Comment by lvjie0519** [comment]
issue暂且关闭，如果测试发现相同崩溃日志，再reopen，如果出现其他崩溃日志，新提issue，谢谢。

**Comment by flingInTheSky** [comment]
问题2我这边也出现了，基本一样的log，无法定位到具体原因。找了个类似的问题：https://github.com/facebook/react-native/issues/19233  不知道是否有所帮助。
