### ISSUE TITLE
Device.getDeviceWifi().callMethod和Device.getDeviceWifi().loadProperties报错

### ISSUE THREAD

**Issue by coderLM** [MiEcosystem/miot-plugin-sdk#233]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android]
- 相关模块:[Device]
-米家版本：[5.4.37]
净化器
#### 现象
调用  
Device.getDeviceWifi().loadProperties(propsArr).then(map => {
        });
或
   Device.getDeviceWifi().callMethod('get_prop', propsArr)
            .then(res => console.log('success:', res))
            .catch(err => console.error('failed:', err))
报错
错误日志相同

#### 日志

 com.facebook.react.bridge.NativeArgumentsParseException: MIOTDevice.callMethod got 5 arguments, expected 4
 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355)
 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 	at android.os.Handler.handleCallback(Handler.java:754)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 	at android.os.Looper.loop(Looper.java:163)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
 	at java.lang.Thread.run(Thread.java:760)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
参数个数的问题，请问您使用的是最新apk吗？请确保使用的是最新apk。

**Comment by lvjie0519** [comment]
一般因为小细节的修改，不会增加版本号，以后每发一次apk将会增加版本号，谢谢意见。
