### ISSUE TITLE
sdk更新到最新后  npm start 启动报错

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#396]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Linux]

#### 现象

简单明了地描述一下实际的现象。
从github上面更新到最新后，无法启动了
![image](https://user-images.githubusercontent.com/11848308/54327040-a797b000-4643-11e9-8eef-a2ceb78eaeea.png)

#### 期望

能正常启动

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@uSmile-Y  问题解决了吗？ 看您前一个问题已经可以进入插件了，如果解决了，麻烦说一下解决步骤，这样可以方便其他接入方遇到相同的问题可以参照您的步骤，谢谢~

**Comment by uSmile-Y** [comment]
@lvjie0519 问题没解决，我是回退了版本才能进入插件

**Comment by laohuang88** [comment]
请及时更新sdk

**Comment by codebeautiful** [comment]
我也遇到更新插件后报错，但是和你的有点区别，现在只能退回之前的版本继续开发了

```
error: bundling failed: Error: Unable to resolve module `./native` from `/home/ubuntu/work/react-native/mijia-rn/miot-sdk/Package.js`: The module `./native` could not be found from `/home/ubuntu/work/react-native/mijia-rn/miot-sdk/Package.js`. Indeed, none of these files exist:

  * `/home/ubuntu/work/react-native/mijia-rn/miot-sdk/native(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/home/ubuntu/work/react-native/mijia-rn/miot-sdk/native/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /home/ubuntu/work/react-native/mijia-rn/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [android, dev] projects/xxx.xxx.xxx/index.js ▓░░░░░░░░░░░░░░░ 7.8% (135/483), failed.
```

**Comment by blockdate** [comment]
@codebeautiful 这个错误建议全量更新github上的代码，同时npm start --reset-cache。

我们这边对github上的工程进行了测试，可以正常的work。

**Comment by fgb031102** [comment]
> @codebeautiful 这个错误建议全量更新github上的代码，同时npm start --reset-cache。
> 
> 我们这边对github上的工程进行了测试，可以正常的work。

遇到同样的问题，直接克隆的github上面的全部代码。
新的SDK对node，npm 等有什么版本要求吗？
