### ISSUE TITLE
插件进不去

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#57]
你好，创建完project .提示一个binding属性为空

import React from 'react';
    import {Package,Device,Service,Host} from 'miot';
    import {PackageEvent, DeviceEvent} from 'miot';

    class App extends React.Component{
        render(){
            return null;
        }
    }
    Package.entry(App, ()=>{

    })

插件日志
 BUNDLE  [ios, dev] projects/com.huami.watch3.ios/index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:10.8.20.234 - - [27/Nov/2018:02:50:46 +0000] "GET /projects/com.huami.watch3.ios/index.ios.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "%E7%B1%B3%E5%AE%B6Beta/4.5.0.3 CFNetwork/902.2 Darwin/17.7.0"
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/scope/index.js:867:13)
    at BlockScoping.updateScopeInfo (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/context.js:118:16)
 BUNDLE  [ios, dev] projects/com.huami.watch3.ios/index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by dingshaoran** [comment]
请不要提交两个重复的问题，您这个是怎么创建的插件，很可能是代码里有错误

**Comment by dingshaoran** [comment]
用 android 试试，我用命令npm run create -- --models zimi.clock.myk01 com.zimi.clockd创建了一个项目，添加 text 后可以显示内容
