### ISSUE TITLE
android 调试10005 进不了插件

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#643]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

android 5.5.10 (Build 62865) - 82.45 MB 更新于: 2019-04-23 15:58
该版本调试10005 进不了插件
错误如下
![image](https://user-images.githubusercontent.com/5235769/56638991-27348800-66a2-11e9-97c1-a69a12f107cc.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、请查看Android studio 的Logcat中的输出日志，希望能提供下log日志，谢谢。

**Comment by smalld2006** [comment]
04-25 10:34:30.549 20687-20687/com.xiaomi.smarthome:plugin0 E/unknown:ReactNative: Tried to remove non-existent frame callback
04-25 10:34:30.559 20687-20687/com.xiaomi.smarthome:plugin0 I/RN_TIMESTAMP: runtime plugin ready : 1556159670559
04-25 10:34:30.690 20687-20687/com.xiaomi.smarthome:plugin0 D/rn-plugin: onSaveInstanceState
04-25 10:34:30.868 20687-21297/com.xiaomi.smarthome:plugin0 E/ReactNativeJNI: Got JS Exception: Attempted to redefine property 'setDeviceProp'. (http://localhost:8081/projects/com.midr.rvmirror/index.delta?platform=android&dev=true&minify=false:98624)
04-25 10:34:30.870 20687-21297/com.xiaomi.smarthome:plugin0 E/ReactNativeJS: NativeModuleCallExceptionHandler
    com.facebook.react.devsupport.JSException: Attempted to redefine property 'setDeviceProp'. (http://localhost:8081/projects/com.midr.rvmirror/index.delta?platform=android&dev=true&minify=false:98624)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: Attempted to redefine property 'setDeviceProp'. (http://localhost:8081/projects/com.midr.rvmirror/index.delta?platform=android&dev=true&minify=false:98624)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194) 
        at java.lang.Thread.run(Thread.java:764) 
04-25 10:34:30.888 20687-20687/com.xiaomi.smarthome:plugin0 D/ReactNative: CatalystInstanceImpl.destroy() start
04-25 10:34:30.897 20687-21297/com.xiaomi.smarthome:plugin0 E/ReactNativeJS: NativeModuleCallExceptionHandler
    java.lang.RuntimeException: Error calling AppRegistry.runApplication
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194) 
        at java.lang.Thread.run(Thread.java:764) 
04-25 10:34:30.916 20687-20687/com.xiaomi.smarthome:plugin0 D/ReactNative: CatalystInstanceImpl.destroy() start
04-25 10:34:30.926 20687-21292/com.xiaomi.smarthome:plugin0 D/ReactNative: CatalystInstanceImpl.destroy() end

**Comment by gaopingfly** [comment]
> before issue：（不用回答）
> 
> ### IPA/APK 是否更新到最新？
> ### SDK 是否更新到最新？
> ### Check 文档了吗？
> ### 是否尝试搜索issue？
> #### 环境
> * 电脑操作系统:[eg.Windows/Mac OS/Linux]
> * 手机系统:[eg.Android 8.1/iOS 11.0]
> * SDK分支: [eg.master/10000/...]
> * 相关模块:[eg.Host/Service/Account]
> 
> #### 现象
> android 5.5.10 (Build 62865) - 82.45 MB 更新于: 2019-04-23 15:58
> 该版本调试10005 进不了插件
> 错误如下
> ![image](https://user-images.githubusercontent.com/5235769/56638991-27348800-66a2-11e9-97c1-a69a12f107cc.png)
> 
> #### 期望
> 简单明了地描述一下期望的表现。
> 
> #### 其他的上下文/日志/截图
> 提供更多的上下文，有日志或者截图更好。
> 
> #### 尝试过的解决办法
> 尝试过哪些操作？
> 
> ### 不要贴大段代码❗️

兄弟，切10010分支吧，用新apk。  目前还能用。

**Comment by gaopingfly** [comment]
哎，最近稳定性比较差啊。我也遇到这个问题了。求解。
用10004分支，ios蓝牙无法连接。Android是好的。
用10010分支，npm start时，提示用的是10005，然后ios好了，android连插件页面都进不去了。
用锤子的android 6.0手机是好的。
用小米Max2的android 7.1手机就出现问题了。

**Comment by uSmile-Y** [comment]
我android也进不去 #657

**Comment by lvjie0519** [comment]
@smalld2006 @uSmile-Y   运行 xiaomi.demo 也一样出现 如上错误，无法进入插件吗？   我这边一直无法复现。

**Comment by smalld2006** [comment]
哦,那么如何加载demo插件呢?

**Comment by uSmile-Y** [comment]
我试了 demo一样的问题 反馈给他们了 平台方正在处理

**Comment by lvjie0519** [comment]
已修复，请更新sdk到10010分支， 这里暂时关闭，请同意关注如下issue
https://github.com/MiEcosystem/miot-plugin-sdk/issues/658
