### ISSUE TITLE
android不支持支持喜马拉雅api

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#685]
#### 公司名称

创米

#### 项目名称 / 项目ID
小米网络收音机、小米网络收音机增强版
chuangmi.radio.v1、chuangmi.radio.v2

#### 环境
- 电脑操作系统: Mac
- 手机系统: Android
- SDK分支: master
- 相关模块: XimalayaSDK

#### 现象

android不支持喜马拉雅api

#### 期望

android能使用喜马拉雅api

**Comment by lvjie0519** [comment]
@yanmin0220  android上使用报什么错误吗？ 我看Android这边有支持。

**Comment by yanmin0220** [comment]
> @yanmin0220 android上使用报什么错误吗？ 我看Android这边有支持。


2019-04-30 09:59:35.458 8887-10235/com.xiaomi.smarthome:plugin1 E/ReactNativeJS: NativeModuleCallExceptionHandler
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.xiaomi.smarthome.framework.plugin.rn.nativemodule.MIOTXimalayaModule.init(SourceFile:41)
        at com.xiaomi.smarthome.framework.plugin.rn.nativemodule.MIOTXimalayaModule.registry(SourceFile:114)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
        at java.lang.Thread.run(Thread.java:764)
-----------------------
2019-04-30 09:59:35.481 8887-10235/com.xiaomi.smarthome:plugin1 E/ReactNativeJS: NativeModuleCallExceptionHandler
    com.facebook.react.bridge.NativeArgumentsParseException: MIOTXimalaya.requestXMData got 3 arguments, expected 4
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:355)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:31)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:194)
        at java.lang.Thread.run(Thread.java:764)


有喜马拉雅api这一块的文档吗，我看了下文档库中没有
可否加微信yanmin0220详聊

**Comment by yanmin0220** [comment]
```
2019-04-30 10:45:31.756 18031-18708/com.xiaomi.smarthome:core D/MIIO: {"code":0,"message":"","result":{"latest_info":[{"plugin_id":1000031,"plugin_package_id":1010814,"version":10,"sdk_version":10005,"change_log":"1.UI优化","download_url":"https://cdn.awsusor0.fds.api.mi-img.com/rn-plugins/2019-04-29/signed_10005_1000031_10_ANDROID_bundle_646e6ca3e20bf227239d9c018dcf2e33.zip","size":801028,"model":"chuangmi.plug.hmi205","force_update_status":0,"status":4,"md5sum":"646e6ca3e20bf227239d9c018dcf2e33","gray_info":"[]","platform":1,"create_time":1556504318967}],"backup_info":[{"model":"chuangmi.plug.hmi205","new_version":1,"plugin_id":64,"package_id":533,"force":0,"version":18,"change_log":"1.UI优化","download_url":"http://cdn.awsusor0.fds.api.mi-img.com/default/chuangmi.plug.hmi205_2018071814220779875.zip?Expires=1563134112000&GalaxyAccessKeyId=5721718224520&Signature=NMCzwAhkLXfqgbfQJvozXQq3CW8=","safe_url":"https://cdn.awsusor0.fds.api.mi-img.com/default/chuangmi.plug.hmi205_2018071814220779875.zip?Expires=1564368332000&GalaxyAccessKeyId=5721718224520&Signature=R3gUTgqOu4/oElb+QUoXnxisHLI=","package_name":"chuangmi.plug.hmi205","length":1313593,"type":"MPK","api_level":5}]}}
```
https://cdn.awsusor0.fds.api.mi-img.com/rn-plugins/2019-04-29/signed_10005_1000031_10_ANDROID_bundle_646e6ca3e20bf227239d9c018dcf2e33.zip地址
提示Bucket Not Found: Make sure you have created bucket in current region, request-id=eb5db5fd-71c4-ac30-0000-016a6bdf58c5，需要服务器看一下

**Comment by lvjie0519** [comment]
@yanmin0220 看了Android这边代码，喜马拉雅模块确实存在问题，预计这周内修复，谢谢。

**Comment by lvjie0519** [comment]
该问题线下沟通已解决。
