### ISSUE TITLE
可以正常创建并运行新工程，但是无法显示加载demo？

### ISSUE THREAD

**Issue by xuhongv** [MiEcosystem/miot-plugin-sdk#962]
**是否为新品**
 新品 

**关联的产品model**
zmd.light.smartlight

**项目ID**
无项目ID

**企业名称（必填）**
成都智明达科技有限公司

**环境**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [master]
- 相关模块:[Host]

**现象**
 - 通过 npm create创建一个新的项目可以成功显示在 ios app上面，但是在运行 project文件夹下自带的demo时候，报错log如下：

`error: bundling failed: Error: Unable to resolve module `react-native-root-toast` from `/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/projects/com.xiaomi.demo/Main/UIComponent/ToastExample.js`: Module does not exist in the module map
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:1476)
    at ResolutionRequest.resolveDependency (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/mac/Desktop/ReactNativeDemo/miot-plugin-sdk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] projects/com.xiaomi.demo/index.ios.js ▓░░░░░░░░░░░░░░░ 10.9% (465/1411), failed.
`

**期望（必填）**
我只想跑起来这个  `com.xiaomo.demo`这个工程，观看预览。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/25237870/59242171-21d4d200-8c3d-11e9-98d8-9529d55fac2a.png)

**尝试过的解决办法**
 不知道如何解决

**Comment by zhuxinleibandou** [comment]
我也遇到了同样的错误，Android上运行米家demo会报错，iOS没问题。10012版本。期望能解决一下。好像和ToastExample有关。


![DA385BFD-E1E9-4A78-B237-90AA464EC4B6](https://user-images.githubusercontent.com/18374383/59247112-e80dc680-8c50-11e9-954d-f98b1c256b5b.png)

**Comment by santcool** [comment]
在com.xiaomi.demo下，执行npm install后，重新npm start即可
